"""Shared ICS (RFC 5545) calendar generation for the campus scrapers.

The UTM / UTSC / ArtsCI scrapers all emit identically-structured all-day
calendars that differ only in their PRODID, calendar name, UID domain and
source URL — captured here as keyword arguments.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timedelta
from pathlib import Path

import pytz
from icalendar import Calendar, Event

TORONTO_TZ = pytz.timezone("America/Toronto")


def write_all_day_calendar(
    events: list[dict],
    output_path: Path,
    *,
    prodid: str,
    calname: str,
    uid_domain: str,
    source_url: str,
) -> None:
    """Write a VCALENDAR file with one all-day VEVENT per event.

    Each event dict must provide: ``start_date`` (``datetime.date``),
    ``end_date`` (``datetime.date`` or ``None``), ``session`` (str),
    ``summary`` (str) and ``description`` (str).

    DTEND is exclusive (the day *after* the inclusive end date) per RFC 5545.
    UIDs are SHA-256 stable so repeated runs produce idempotent output.
    """
    cal = Calendar()
    cal.add("prodid", prodid)
    cal.add("version", "2.0")
    cal.add("calscale", "GREGORIAN")
    cal.add("method", "PUBLISH")
    cal.add("x-wr-calname", calname)
    cal.add("x-wr-timezone", "America/Toronto")
    cal.add("x-wr-caldesc", "Generated by UofT calendar Bot")
    # Suggest clients refresh once per day (RFC 7986 + Apple compat)
    cal.add("refresh-interval", timedelta(days=1))
    cal.add("x-published-ttl", "P1D")

    now_utc = datetime.now(pytz.utc)

    for evt in events:
        vevent = Event()
        vevent.add("summary", evt["summary"])
        # DTSTART: all-day — pass datetime.date not datetime.datetime
        vevent.add("dtstart", evt["start_date"])

        # DTEND: exclusive day after the inclusive end date
        inclusive_end = evt["end_date"] if evt["end_date"] else evt["start_date"]
        vevent.add("dtend", inclusive_end + timedelta(days=1))

        # Stable UID (SHA-256 of key fields so repeat runs are idempotent)
        uid_src = (
            f"{evt['start_date'].isoformat()}"
            f"|{evt['session']}"
            f"|{evt['description'][:120]}"
        )
        uid_hex = hashlib.sha256(uid_src.encode()).hexdigest()[:24]
        vevent.add("uid", f"{uid_hex}@{uid_domain}")

        vevent.add("dtstamp", now_utc)
        vevent.add(
            "description",
            (
                f"Session: {evt['session']}\n"
                f"{evt['description']}\n\n"
                f"Source: {source_url}\n"
                "Generated by U-of-T-Calendar-Bot "
                "(student project — not affiliated with the University of Toronto)"
            ),
        )
        vevent.add("url", source_url)
        cal.add_component(vevent)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(cal.to_ical())
