#!/usr/bin/env python3
"""
ICS Program-Event Filter  (Experimental)
=========================================
Reads each campus ICS file and produces a filtered variant that removes
program-selection events — dates relevant only to students not yet in a
declared program / major / specialist / minor.

WARNING: Uses keyword matching on SUMMARY.  False positives and false
negatives are possible.  Always verify important dates on the official
campus registrar page.

Output: public/calendar/{artsci,utm,utsc}-filtered.ics
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

SCRIPT_DIR   = Path(__file__).parent
CALENDAR_DIR = SCRIPT_DIR.parent / "public" / "calendar"

# Keywords that identify program-selection / program-admission events.
# Matched case-insensitively against the unfolded SUMMARY value.
PROGRAM_KEYWORDS: list[str] = [
    r"limited program",           # ArtsCI: limited-enrolment program rounds
    r"program selection",         # UTM: program selection request period
    r"invitation to a program",   # UTM: program invitation deadline
    r"decision iteration",        # ArtsCI: Collaborative Life Science rounds
    r"collaborative life science",# ArtsCI: CLS program events
]
FILTER_RE = re.compile("|".join(PROGRAM_KEYWORDS), re.IGNORECASE)

CAMPUS_FILES: list[tuple[str, str, str]] = [
    ("artsci.ics", "artsci-filtered.ics", "ArtsCI Important Dates (Program-Filtered)"),
    ("utm.ics",    "utm-filtered.ics",    "UTM Important Dates (Program-Filtered)"),
    ("utsc.ics",   "utsc-filtered.ics",   "UTSC Important Dates (Program-Filtered)"),
]

# ---------------------------------------------------------------------------
# ICS text-level parsing helpers
# ---------------------------------------------------------------------------

def unfold(lines: list[str]) -> list[str]:
    """Merge RFC 5545 folded continuations into logical lines."""
    result: list[str] = []
    for raw in lines:
        if raw and raw[0] in (" ", "\t") and result:
            result[-1] = result[-1].rstrip("\r\n") + raw[1:].rstrip("\r\n") + "\r\n"
        else:
            result.append(raw)
    return result


def get_summary(event_lines: list[str]) -> str:
    """Return the unfolded SUMMARY value from a list of VEVENT logical lines."""
    for ln in event_lines:
        if ln.upper().startswith("SUMMARY:"):
            return ln[8:].rstrip("\r\n")
    return ""


# ---------------------------------------------------------------------------
# Per-campus filter
# ---------------------------------------------------------------------------

def filter_campus(src: Path, dst: Path, cal_name: str) -> tuple[int, int]:
    raw   = src.read_text(encoding="utf-8", errors="replace").splitlines(keepends=True)
    lines = unfold(raw)

    output: list[str] = []
    in_event           = False
    event_buf: list[str] = []
    kept = removed     = 0

    for line in lines:
        tag = line.strip().upper()
        if tag == "BEGIN:VEVENT":
            in_event  = True
            event_buf = [line]
        elif tag == "END:VEVENT":
            event_buf.append(line)
            in_event = False
            if FILTER_RE.search(get_summary(event_buf)):
                removed += 1
            else:
                output.extend(event_buf)
                kept += 1
        elif in_event:
            event_buf.append(line)
        else:
            upper = line.upper()
            if upper.startswith("X-WR-CALNAME:"):
                output.append(f"X-WR-CALNAME:{cal_name}\r\n")
            elif upper.startswith("X-WR-CALDESC:"):
                output.append(
                    "X-WR-CALDESC:Program-selection events filtered (experimental)."
                    " May have false positives."
                    " Generated by UofT calendar Bot\r\n"
                )
            else:
                output.append(line)

    dst.write_text("".join(output), encoding="utf-8")
    return kept, removed


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    errors = 0
    for src_name, dst_name, cal_name in CAMPUS_FILES:
        src = CALENDAR_DIR / src_name
        dst = CALENDAR_DIR / dst_name
        if not src.exists():
            print(f"SKIP  {src_name} (not found)")
            errors += 1
            continue
        kept, removed = filter_campus(src, dst, cal_name)
        print(f"OK    {src_name} → {dst_name}  (kept {kept}, removed {removed})")
    if errors:
        sys.exit(1)


if __name__ == "__main__":
    main()
